version: "3"

env:
   EXPORTER_VERSION:
     sh: cat VERSION

tasks:
  build:
    desc: Build app
    cmds:
      - go build --ldflags '-extldflags "-static"' prometheus-libvirt-exporter.go
  package:
    desc: Build and make dist
    env:
      EXPORTER_VERSION:
        sh: cat VERSION
    cmds:
      - goreleaser release --clean --snapshot